{"id":"node_modules/rxjs/src/internal/util/ArgumentOutOfRangeError.ts","dependencies":[{"name":"C:\\Users\\a875232\\Documents\\rxjs-practice\\node_modules\\rxjs\\tsconfig.json","includedInParent":true,"mtime":1658249596656},{"name":"C:\\Users\\a875232\\Documents\\rxjs-practice\\package.json","includedInParent":true,"mtime":1658249837276},{"name":"C:\\Users\\a875232\\Documents\\rxjs-practice\\node_modules\\rxjs\\package.json","includedInParent":true,"mtime":1658249596644},{"name":"./createErrorClass","loc":{"line":4,"column":35,"index":157},"parent":"C:\\Users\\a875232\\Documents\\rxjs-practice\\node_modules\\rxjs\\src\\internal\\util\\ArgumentOutOfRangeError.ts","resolved":"C:\\Users\\a875232\\Documents\\rxjs-practice\\node_modules\\rxjs\\src\\internal\\util\\createErrorClass.ts"}],"generated":{"js":"\"use strict\";\r\nObject.defineProperty(exports, \"__esModule\", { value: true });\r\nexports.ArgumentOutOfRangeError = void 0;\r\nconst createErrorClass_1 = require(\"./createErrorClass\");\r\nexports.ArgumentOutOfRangeError = (0, createErrorClass_1.createErrorClass)((_super) => function ArgumentOutOfRangeErrorImpl() {\r\n    _super(this);\r\n    this.name = 'ArgumentOutOfRangeError';\r\n    this.message = 'argument out of range';\r\n});\r\n"},"sourceMaps":{"js":{"version":3,"file":"ArgumentOutOfRangeError.js","sourceRoot":"","sources":["node_modules/rxjs/src/internal/util/ArgumentOutOfRangeError.ts"],"names":[],"mappings":";;;AAAA,yDAAsD;AAsBzC,QAAA,uBAAuB,GAAgC,IAAA,mCAAgB,EAClF,CAAC,MAAM,EAAE,EAAE,CACT,SAAS,2BAA2B;IAClC,MAAM,CAAC,IAAI,CAAC,CAAC;IACb,IAAI,CAAC,IAAI,GAAG,yBAAyB,CAAC;IACtC,IAAI,CAAC,OAAO,GAAG,uBAAuB,CAAC;AACzC,CAAC,CACJ,CAAC","sourcesContent":["import { createErrorClass } from './createErrorClass';\n\nexport interface ArgumentOutOfRangeError extends Error {}\n\nexport interface ArgumentOutOfRangeErrorCtor {\n  /**\n   * @deprecated Internal implementation detail. Do not construct error instances.\n   * Cannot be tagged as internal: https://github.com/ReactiveX/rxjs/issues/6269\n   */\n  new (): ArgumentOutOfRangeError;\n}\n\n/**\n * An error thrown when an element was queried at a certain index of an\n * Observable, but no such index or position exists in that sequence.\n *\n * @see {@link elementAt}\n * @see {@link take}\n * @see {@link takeLast}\n *\n * @class ArgumentOutOfRangeError\n */\nexport const ArgumentOutOfRangeError: ArgumentOutOfRangeErrorCtor = createErrorClass(\n  (_super) =>\n    function ArgumentOutOfRangeErrorImpl(this: any) {\n      _super(this);\n      this.name = 'ArgumentOutOfRangeError';\n      this.message = 'argument out of range';\n    }\n);\n"]}},"error":null,"hash":"4078b3a7015e62b42759de1ea46e9e20","cacheData":{"env":{}}}